#!/usr/bin/env node
// Emits docs/data.js from the vendored QuestData.json + LgMonsters.json.
//
// Those two files are copies of the MHGU Quest Randomizer's canonical data. When they
// change over there, re-copy them here and re-run this script — there is no automatic
// sync, deliberately (see CLAUDE.md).
//
//   node tools/build-data.js
//
// Output is a single `window.MHGU_BINGO_DATA = {...}` assignment, matching the
// randomizer's data.js convention so the browser needs no module loader.

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const ROOT = path.join(__dirname, "..");
const QUEST_SRC = path.join(ROOT, "QuestData.json");
const MONSTER_SRC = path.join(ROOT, "LgMonsters.json");
// Vendored from MHGU Talisman Bingo, which is where these tables are maintained.
const TAL_NAME_SRC = path.join(ROOT, "talisman.json");
const TAL_TABLE_SRC = path.join(ROOT, "talisman_charm_table.json");
const SKILL_SRC = path.join(ROOT, "skills.json");
const OUT = path.join(ROOT, "docs", "data.js");

// Every quest field bingo actually reads. Hunter Arts are dropped entirely (bingo rolls
// none), as are the Arena-only ArenaWeapons/ArenaBiases arrays — arena quests still
// appear as Quest goals, just without their per-quest weapon restriction.
const QUEST_FIELDS = [
  "Type", "Name", "Main", "Monster", "Monsters", "Level", "Locale",
  "LgMonster", "Prowler", "Hyper", "Egg", "Gathering", "SmMonsters",
  "Capture", "OnSite", "OneFaint", "Key",
];

function read(file) {
  const raw = fs.readFileSync(file, "utf8");
  const parsed = JSON.parse(raw);
  if (!Array.isArray(parsed)) throw new Error(`${path.basename(file)} is not a JSON array`);
  return { raw, parsed };
}

function trimQuest(q) {
  const out = {};
  for (const key of QUEST_FIELDS) {
    if (key === "Monsters") out.Monsters = Array.isArray(q.Monsters) ? q.Monsters : [];
    else if (key === "Level") out.Level = q.Level | 0;
    else if (typeof q[key] === "boolean") out[key] = q[key];
    else out[key] = q[key] == null ? "" : q[key];
  }
  return out;
}

const quests = read(QUEST_SRC);
const monsters = read(MONSTER_SRC);

// ── Talismans ───────────────────────────────────────────────────────────────
// Three kinds of talisman square: the ten rarities by name, the four slot counts, and a
// skill by name. The skill list is DERIVED, not chosen: a tree only qualifies if it can
// roll on all four talisman tiers, which makes it reachable off any talisman you meld.
// The other 128 eligible trees are tier-locked and would sit unmarked for a long time.
//
// Table shape is {tier: [[lo1,hi1,lo2,hi2], ...]} indexed by tree id; a tree can roll in
// that tier when either upper bound is above zero. Deviant trees are cut for the same
// reason Talisman Bingo cuts them — "Bloodbath X" is not a readable square.
const TIERS = ["mystery", "shining", "timeworn", "enduring"];
const DEV_LO = 144, DEV_HI = 179;

function readJson(file) {
  const raw = fs.readFileSync(file, "utf8");
  return { raw, parsed: JSON.parse(raw) };
}

const talNames = readJson(TAL_NAME_SRC);
const talTable = readJson(TAL_TABLE_SRC);
const skillNames = readJson(SKILL_SRC);

function allTierSkills() {
  const rowsFor = (t) => talTable.parsed[t] || [];
  const canRoll = (t, id) => {
    const row = rowsFor(t)[id];
    return !!row && Math.max(row[1] | 0, row[3] | 0) > 0;
  };
  const ids = Object.keys(skillNames.parsed).map(Number).sort((a, b) => a - b);
  return ids
    .filter(id => !(id >= DEV_LO && id <= DEV_HI))
    .filter(id => TIERS.every(t => canRoll(t, id)))
    .map(id => skillNames.parsed[id]);
}

const talismans = {
  names: talNames.parsed,
  slots: [0, 1, 2, 3],
  skills: allTierSkills(),
};

// Hashing the raw source bytes (not the trimmed output) means any upstream data edit
// shifts the version even if it touches a field bingo drops. The version rides along in
// every seed's fingerprint, so a data rebuild makes old seeds warn instead of silently
// producing a different card.
const dataVersion = crypto
  .createHash("sha256")
  .update(quests.raw)
  .update(monsters.raw)
  .update(talNames.raw)
  .update(talTable.raw)
  .update(skillNames.raw)
  .digest("hex")
  .slice(0, 12);

const data = {
  dataVersion,
  quests: quests.parsed.map(trimQuest),
  monsters: monsters.parsed.map(m => ({ MonsterName: m.MonsterName, Species: m.Species })),
  talismans,
};

const banner = "// Auto-generated by tools/build-data.js. Do not edit by hand.\n";
fs.writeFileSync(OUT, banner + "window.MHGU_BINGO_DATA = " + JSON.stringify(data) + ";\n");

const kb = (fs.statSync(OUT).size / 1024).toFixed(0);
console.log(`Wrote docs/data.js — ${data.quests.length} quests, ${data.monsters.length} monsters, ` +
  `${Object.keys(talismans.names).length} talisman rarities, ${talismans.skills.length} all-tier skills, ` +
  `dataVersion ${dataVersion} (${kb} KB)`);
