#!/usr/bin/env node
// Emits docs/data.js from the vendored QuestData.json + LgMonsters.json.
//
// Those two files are copies of the MHGU Quest Randomizer's canonical data. When they
// change over there, re-copy them here and re-run this script — there is no automatic
// sync, deliberately (see CLAUDE.md).
//
//   node tools/build-data.js
//
// Output is a single `window.MHGU_BINGO_DATA = {...}` assignment, matching the
// randomizer's data.js convention so the browser needs no module loader.

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const ROOT = path.join(__dirname, "..");
const QUEST_SRC = path.join(ROOT, "QuestData.json");
const MONSTER_SRC = path.join(ROOT, "LgMonsters.json");
const OUT = path.join(ROOT, "docs", "data.js");

// Every quest field bingo actually reads. Hunter Arts are dropped entirely (bingo rolls
// none), as are the Arena-only ArenaWeapons/ArenaBiases arrays — arena quests still
// appear as Quest goals, just without their per-quest weapon restriction.
const QUEST_FIELDS = [
  "Type", "Name", "Main", "Monster", "Monsters", "Level", "Locale",
  "LgMonster", "Prowler", "Hyper", "Egg", "Gathering", "SmMonsters",
  "Capture", "OnSite", "OneFaint", "Key",
];

function read(file) {
  const raw = fs.readFileSync(file, "utf8");
  const parsed = JSON.parse(raw);
  if (!Array.isArray(parsed)) throw new Error(`${path.basename(file)} is not a JSON array`);
  return { raw, parsed };
}

function trimQuest(q) {
  const out = {};
  for (const key of QUEST_FIELDS) {
    if (key === "Monsters") out.Monsters = Array.isArray(q.Monsters) ? q.Monsters : [];
    else if (key === "Level") out.Level = q.Level | 0;
    else if (typeof q[key] === "boolean") out[key] = q[key];
    else out[key] = q[key] == null ? "" : q[key];
  }
  return out;
}

const quests = read(QUEST_SRC);
const monsters = read(MONSTER_SRC);

// Hashing the raw source bytes (not the trimmed output) means any upstream data edit
// shifts the version even if it touches a field bingo drops. The version rides along in
// every seed's fingerprint, so a data rebuild makes old seeds warn instead of silently
// producing a different card.
const dataVersion = crypto
  .createHash("sha256")
  .update(quests.raw)
  .update(monsters.raw)
  .digest("hex")
  .slice(0, 12);

const data = {
  dataVersion,
  quests: quests.parsed.map(trimQuest),
  monsters: monsters.parsed.map(m => ({ MonsterName: m.MonsterName, Species: m.Species })),
};

const banner = "// Auto-generated by tools/build-data.js. Do not edit by hand.\n";
fs.writeFileSync(OUT, banner + "window.MHGU_BINGO_DATA = " + JSON.stringify(data) + ";\n");

const kb = (fs.statSync(OUT).size / 1024).toFixed(0);
console.log(`Wrote docs/data.js — ${data.quests.length} quests, ${data.monsters.length} monsters, dataVersion ${dataVersion} (${kb} KB)`);
